import Header from "@/components/header/Header";
import "./globals.css";
import SideBar from "@/components/sidebar/Sidebar";
import type { Metadata } from "next";
import Footer from "@/components/footer/Footer";

import store from "@/store/index";
import { Providers } from "./provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="main">
            <div className="child">
              <SideBar />
            </div>
            <main className="content">{children}</main>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
